name: Run Python Script Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 12:00 AM UTC
  workflow_dispatch:      # Optional: allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        run: python rsi.py
