name: Run Notebook

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 12:00 AM UTC daily

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install papermill

      - name: Run notebook
        run: |
          papermill rsi.ipynb
